version: "3.7"

services:
  app:
    build: .
    container_name: mosquiTrack
    restart: always
    environment:
      PORT: ${PORT}
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "5432:3000"